// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TranslationsApi.DAL;

namespace TranslationsApi.DAL.Migrations
{
    [DbContext(typeof(TranslationsApiContext))]
    [Migration("20191226170138_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TranslationsApi.Core.Models.Key", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("KeyName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KeyValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId", "KeyName");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("TranslationsApi.Core.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LangCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LangCode")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("TranslationsApi.Core.Models.Key", b =>
                {
                    b.HasOne("TranslationsApi.Core.Models.Language", "Language")
                        .WithMany("Keys")
                        .HasForeignKey("LanguageId")
                        .HasConstraintName("Key_Language")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
